/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Transaction, Category } from './types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    name: 'Makanan & Minuman',
    iconName: 'UtensilsCrossed',
    colorClass: 'amber',
    budget: 4000000,
  },
  {
    id: 'cat-2',
    name: 'Transportasi',
    iconName: 'Car',
    colorClass: 'blue',
    budget: 1500000,
  },
  {
    id: 'cat-3',
    name: 'Belanja',
    iconName: 'ShoppingBag',
    colorClass: 'emerald',
    budget: 3500000,
  },
  {
    id: 'cat-4',
    name: 'Hiburan',
    iconName: 'Film',
    colorClass: 'purple',
    budget: 1000000,
  },
  {
    id: 'cat-5',
    name: 'Tagihan & Sewa',
    iconName: 'Receipt',
    colorClass: 'slate',
    budget: 5000000,
  },
  {
    id: 'cat-6',
    name: 'Kesehatan',
    iconName: 'HeartPulse',
    colorClass: 'rose',
    budget: 1200000,
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-1',
    type: 'income',
    amount: 3500000,
    category: 'Gaji',
    date: '2026-06-07',
    time: '07:15',
    description: 'Gaji Bulanan Alexander',
    account: 'Transfer Bank',
  },
  {
    id: 'tx-2',
    type: 'expense',
    amount: 124500,
    category: 'Belanja',
    date: '2026-06-06',
    time: '14:30',
    description: 'Belanja Mingguan Pasar Swalayan',
    account: 'Visa',
  },
  {
    id: 'tx-3',
    type: 'expense',
    amount: 42500,
    category: 'Makanan & Minuman',
    date: '2026-06-07',
    time: '12:45',
    description: 'Makan Siang - Green Bistro',
    account: 'Mastercard',
  },
  {
    id: 'tx-4',
    type: 'income',
    amount: 850000,
    category: 'Proyek Freelance',
    date: '2026-06-07',
    time: '09:15',
    description: 'Desain Landing Page',
    account: 'Transfer Bank',
  },
  {
    id: 'tx-5',
    type: 'expense',
    amount: 129990,
    category: 'Belanja',
    date: '2026-06-06',
    time: '16:20',
    description: 'Pembelian Modern Retail Co.',
    account: 'Visa',
  },
  {
    id: 'tx-6',
    type: 'expense',
    amount: 5800,
    category: 'Makanan & Minuman',
    date: '2026-06-05',
    time: '10:30',
    description: 'Kopi Susu Kafe Sore',
    account: 'Mastercard',
  },
  {
    id: 'tx-7',
    type: 'expense',
    amount: 45000,
    category: 'Kesehatan',
    date: '2026-06-04',
    time: '15:00',
    description: 'Kebugaran Langganan Gym',
    account: 'Auto-debet',
  },
  {
    id: 'tx-8',
    type: 'expense',
    amount: 2750,
    category: 'Transportasi',
    date: '2026-06-06',
    time: '11:30',
    description: 'Transportasi Kota Commuter',
    account: 'Apple Pay',
  },
  {
    id: 'tx-9',
    type: 'expense',
    amount: 95400,
    category: 'Tagihan & Sewa',
    date: '2026-06-06',
    time: '08:00',
    description: 'Tagihan Listrik Rumah',
    account: 'Auto-debet',
  },
  {
    id: 'tx-10',
    type: 'expense',
    amount: 1450000, // Over budget simulation for Hiburan
    category: 'Hiburan',
    date: '2026-06-03',
    time: '19:00',
    description: 'Konser Musik Akhir Pekan',
    account: 'Visa',
  },
];
